title = "Pier"

[port]
http = 44544
pprof = 44555

[log]
level = "info"
dir = "logs"
filename = "pier.log"
report_caller = false

[mode]
type = "relay" # relay, direct or union
[mode.relay]
addr = "localhost:60011"
bootstraps = []
quorum = 2
validators = [
    "0x000f1a7a08ccc48e5d30f80850cf1cf283aa3abd",
    "0xe93b92f1da08f925bdee44e91e7768380ae83307",
    "0xb18c8575e3284e79b92100025a31378feb8100d6",
    "0x856E2B9A5FA82FD1B031D1FF6863864DBAC7995D",
]
[mode.direct]
peers = []

[mode.union]
connectors = []

[appchain]
plugin = "appchain_plugin"
config = "fabric"
